apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
  labels:
    app: demo
spec:
  containers:
  - name: linux-nginx-1
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
  labels:
    app: demo
spec:
  containers:
  - name: linux-nginx-2
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-3
  labels:
    app: demo
spec:
  containers:
  - name: linux-nginx-3
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-4
  labels:
    app: demo
spec:
  containers:
  - name: linux-nginx-4
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"