apiVersion: v1
kind: Pod
metadata:
  name: demo-container-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-container
    image: nginx
    ports:
    - containerPort: 80

    resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"

  - name: firefox-container
    image: linuxserver/firefox
    ports:
    - containerPort: 3000

    resources:
      requests:
        cpu: "150m"
        memory: "192Mi"
      limits:
        cpu: "700m"
        memory: "320Mi" 