apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  storageClassName: andy
  volumeMode: Filesystem
  accessmodes:
  - ReadWriteMany
  azureFile:
    secretName: secret-dev
    shareName: jackel
  capacity:
    storage: 4Gi